# Generated by Django 4.2.6 on 2023-10-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_name', models.CharField(max_length=100)),
                ('res_dec', models.TextField()),
                ('rec_image', models.ImageField(null=True, upload_to='rec_folder')),
            ],
        ),
    ]
