# Generated by Django 4.2.6 on 2023-10-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0003_rec_user1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rec',
            old_name='user1',
            new_name='user',
        ),
    ]
